apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k3s-local-fio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: k3s-fio-pod
spec:
  containers:
  - name: fio-container
    image: nixery.dev/shell/fio
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: benchmark-volume
      mountPath: /mnt/localpath
  volumes:
  - name: benchmark-volume
    persistentVolumeClaim:
      claimName: k3s-local-fio-pvc

