apiVersion: v1
kind: ServiceAccount
metadata:
  name: anansi-bench
  namespace: kserve-bench
  labels:
    app.kubernetes.io/name: anansi
    app.kubernetes.io/part-of: anansi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anansi-bench
  labels:
    app.kubernetes.io/name: anansi
    app.kubernetes.io/part-of: anansi
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["revisions", "configurations", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anansi-bench
  labels:
    app.kubernetes.io/name: anansi
    app.kubernetes.io/part-of: anansi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anansi-bench
subjects:
  - kind: ServiceAccount
    name: anansi-bench
    namespace: kserve-bench
