package output

import (
	"encoding/csv"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/zewolfe/anansi/internal/config"
)

// ReportGenerator reads raw results and produces reports.
type ReportGenerator struct {
	inputDir string
}

func NewReportGenerator(inputDir string) *ReportGenerator {
	return &ReportGenerator{inputDir: inputDir}
}

// LoadAllResults reads all CSV files from inputDir/raw/ and returns
// the trial results grouped by config hash.
func (rg *ReportGenerator) LoadAllResults() (map[string][]config.TrialResult, error) {
	rawDir := filepath.Join(rg.inputDir, "raw")

	entries, err := os.ReadDir(rawDir)
	if err != nil {
		return nil, fmt.Errorf("reading raw directory %s: %w", rawDir, err)
	}

	grouped := make(map[string][]config.TrialResult)

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".csv") {
			continue
		}

		path := filepath.Join(rawDir, entry.Name())
		results, err := loadCSV(path)
		if err != nil {
			return nil, fmt.Errorf("loading %s: %w", path, err)
		}

		for _, r := range results {
			grouped[r.ConfigHash] = append(grouped[r.ConfigHash], r)
		}
	}

	if len(grouped) == 0 {
		return nil, fmt.Errorf("no CSV files found in %s", rawDir)
	}

	return grouped, nil
}

// GenerateMarkdownReport writes a human-readable markdown report.
func (rg *ReportGenerator) GenerateMarkdownReport(
	summary *ExperimentSummary,
	outputPath string,
) error {
	var sb strings.Builder

	sb.WriteString("# 🕷 Anansi — Experiment Report\n\n")
	sb.WriteString(fmt.Sprintf("**Configurations:** %d\n\n", summary.TotalConfigs))
	sb.WriteString(fmt.Sprintf("**Total Trials:** %d\n\n", summary.TotalTrials))
	sb.WriteString(fmt.Sprintf("**Errors:** %d\n\n", summary.TotalErrors))
	sb.WriteString("---\n\n")

	// Results table
	sb.WriteString("## Cold-Start Results (TTFT)\n\n")
	sb.WriteString("| Config | Median (s) | P95 (s) | P99 (s) | CI95 (s) | n |\n")
	sb.WriteString("|--------|-----------|---------|---------|----------|---|\n")

	for _, cs := range summary.Configs {
		if cs.TTFT.N == 0 {
			continue
		}
		sb.WriteString(fmt.Sprintf("| %s | %.2f | %.2f | %.2f | [%.2f, %.2f] | %d |\n",
			cs.Label,
			cs.TTFT.Median/1000,
			cs.TTFT.P95/1000,
			cs.TTFT.P99/1000,
			cs.TTFT.CI95Lo/1000,
			cs.TTFT.CI95Hi/1000,
			cs.TTFT.N,
		))
	}

	sb.WriteString("\n---\n\n")

	// Decomposition table
	sb.WriteString("## Cold-Start Decomposition\n\n")
	sb.WriteString("| Config | T_orch (s) | T_runtime (s) | T_load (s) | T_init (s) | Decomp Error |\n")
	sb.WriteString("|--------|-----------|--------------|-----------|-----------|-------------|\n")

	for _, cs := range summary.Configs {
		if cs.TOrch.N == 0 {
			continue
		}
		sb.WriteString(fmt.Sprintf("| %s | %.2f | %.2f | %.2f | %.2f | %.1f%% |\n",
			cs.Label,
			cs.TOrch.Median/1000,
			cs.TServe.Median/1000,
			cs.TLoad.Median/1000,
			cs.TInit.Median/1000,
			cs.DecompErrorPct.Median,
		))
	}

	sb.WriteString("\n---\n\n")

	// Pairwise comparisons
	if len(summary.Comparisons) > 0 {
		sb.WriteString("## Pairwise Comparisons\n\n")
		sb.WriteString("| A | B | Metric | Diff (ms) | p-value | Cohen's d | Sig? |\n")
		sb.WriteString("|---|---|--------|----------|---------|-----------|------|\n")

		for _, comp := range summary.Comparisons {
			sig := ""
			if comp.Significant {
				sig = "✓"
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s | %.1f | %.4f | %.2f | %s |\n",
				comp.ConfigA, comp.ConfigB, comp.Metric,
				comp.DiffMs, comp.PValue, comp.CohensD, sig,
			))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("\n*Report generated by Anansi cold-start benchmarking harness.*\n")

	return os.WriteFile(outputPath, []byte(sb.String()), 0644)
}

// loadCSV reads a single CSV file and parses it into TrialResult structs.
func loadCSV(path string) ([]config.TrialResult, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	reader := csv.NewReader(f)

	// Read header
	header, err := reader.Read()
	if err != nil {
		return nil, fmt.Errorf("reading header: %w", err)
	}

	// Build column index map
	colIdx := make(map[string]int)
	for i, col := range header {
		colIdx[col] = i
	}

	var results []config.TrialResult

	records, err := reader.ReadAll()
	if err != nil {
		return nil, fmt.Errorf("reading records: %w", err)
	}

	for _, row := range records {
		r := config.TrialResult{
			ConfigHash: getCol(row, colIdx, "config_hash"),
			Runtime:    getCol(row, colIdx, "runtime"),
			Format:     getCol(row, colIdx, "format"),
			Model:      getCol(row, colIdx, "model"),
			Scenario:   getCol(row, colIdx, "scenario"),
			Rep:        getColInt(row, colIdx, "rep"),
			T0:         getColInt64(row, colIdx, "t0_ns"),
			T1:         getColInt64(row, colIdx, "t1_ns"),
			T2:         getColInt64(row, colIdx, "t2_ns"),
			T3:         getColInt64(row, colIdx, "t3_ns"),
			T4:         getColInt64(row, colIdx, "t4_ns"),
			T5:         getColInt64(row, colIdx, "t5_ns"),
			T6:         getColInt64(row, colIdx, "t6_ns"),
			T7:         getColInt64(row, colIdx, "t7_ns"),
			TTFT_ms:    getColFloat(row, colIdx, "ttft_ms"),
			TOrch_ms:   getColFloat(row, colIdx, "t_orch_ms"),
			TServe_ms:  getColFloat(row, colIdx, "t_serve_ms"),
			TLoad_ms:   getColFloat(row, colIdx, "t_load_ms"),
			TInit_ms:   getColFloat(row, colIdx, "t_init_ms"),
			GPUMemMB:   getColInt(row, colIdx, "gpu_mem_mb"),
			Error:      getCol(row, colIdx, "error"),
		}
		results = append(results, r)
	}

	return results, nil
}

func getCol(row []string, idx map[string]int, col string) string {
	i, ok := idx[col]
	if !ok || i >= len(row) {
		return ""
	}
	return row[i]
}

func getColInt(row []string, idx map[string]int, col string) int {
	s := getCol(row, idx, col)
	if s == "" {
		return 0
	}
	v, _ := strconv.Atoi(s)
	return v
}

func getColInt64(row []string, idx map[string]int, col string) int64 {
	s := getCol(row, idx, col)
	if s == "" {
		return 0
	}
	v, _ := strconv.ParseInt(s, 10, 64)
	return v
}

func getColFloat(row []string, idx map[string]int, col string) float64 {
	s := getCol(row, idx, col)
	if s == "" {
		return -1
	}
	v, _ := strconv.ParseFloat(s, 64)
	return v
}
