apiVersion: ENC[AES256_GCM,data:vAo=,iv:/PLBEK0Qko98cJhJXoQR0vg7G/yBUZwte2KEtveo6i8=,tag:UivJNwqtljBitFhUqSVofA==,type:str]
kind: ENC[AES256_GCM,data:LvGV4rRg,iv:4fBsJD+iPDQZ8FNd8SNHqJy4ygHl3kN2k1Lctx8YyFs=,tag:sqZBeP1HxFVx/fkUoHNlRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TzrtCD/UIRWQ1n7ggpB3UoAuUSAgjOE=,iv:G6eZw+YLv9+DbP4e94TQmyydRLnusy5RCoTAhMymO7w=,tag:tanDs7igFXedGPIjLA3ZzA==,type:str]
type: ENC[AES256_GCM,data:afpZiy/S,iv:pEZk/Yi719gMyps9HKrgA5owrqCrkka6h4L1jfTfcUs=,tag:Hv/gLZYDqbHv5cFBFtrfsw==,type:str]
data:
    HF_TOKEN: ENC[AES256_GCM,data:tUygOJuujidQa5zPtt9F+6U4UcbzpY11wREVIhnMm6OENi+4qjwxumkVeCSi5bNMSOArvg==,iv:40qjgpc/GUZmZNpHefAoaWCGE28jXjYbupFVWOvHqJM=,tag:tEy3RPJG0P+mQcSCQWm9hA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdjNHNWw3S3pPVFBtYlpx
            c2lzR21nQUYvckxSTG5xTmdkNVZaSmZuMFcwCmNWZnY3Mk80b0k4S2lTd0NBWm52
            UDhMTW45dVp2bG1oUHRhcWFvWnRmUEUKLS0tIE5mYytFTHI0NHE4Wno3Tmp5S29G
            RGw5Vy85REFSTVlFNXdTd1R5Q2dySUkKH1TR4WDnTN4KMS3jyng7jKEZtgVuM1J5
            iSO4iNenzuHcb30CX/kz3WY7RVh+YvnFDKMDzIPWvD42SgjGehzeLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1962cwn3uhn3kp0m9qnk7vvfpzcydfuqdu5v7ph9klxux22n085asg63v9k
    lastmodified: "2026-06-09T12:37:31Z"
    mac: ENC[AES256_GCM,data:tbJmoNXIQVIzGUDbTQOKXn51OH8Ie9MMdU06iD5Hl3djf5PL3FrlhGaE1neugBRlUuo4+2KnZml4+w1klGW9sxkF5SWyWRjTfyqITY0DPpBi1RKaBpiGgrRtVSQJa2y6pBlJP++KNvHG1XZhYsFiurkJ4EWAKS3wmss5IQH+TsA=,iv:gBEmJK+9vg5GCu1JBqFx+V/7DPSM1UbQG0wiQD7kjtc=,tag:IxzYJgFJkHuBuTQIf3ASKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
