apiVersion: ENC[AES256_GCM,data:ges=,iv:feMmpajlm9TjYUINue33eqlCy7Pah9jmo82SNIrm25U=,tag:ZXwx1jNtDEalP5R/pNSKTw==,type:str]
kind: ENC[AES256_GCM,data:E5hcc8JP,iv:v98n0yV/DSMCT1qvjpc2Dd6h6gZ+K4Q5wJzGE7Dp2BI=,tag:CodjFGFy7eTqAvFnbvcU3w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lTFId04rHQLKkRWsiy1PFqMrbr5z,iv:NswK9h8d7B4+pjp4IVZE+6aS0i1su32h7IwW6y77hd8=,tag:kEAQN6prtomMEfmAWpkl7g==,type:str]
    namespace: ENC[AES256_GCM,data:qPJ06qvdz09LR6oB,iv:pVWqtpIuj8vuwzNTUrhYo6hNj6cMS4hfhUUaED+t2BQ=,tag:Hv9RiVvyFfW/gExbBBabvg==,type:str]
    annotations:
        serving.kserve.io/s3-endpoint: ENC[AES256_GCM,data:j5Euqns4W6jXjo5C33a/sM61IN25Id0CkBYkJvPFrII7lw==,iv:EH4dFwGpC5ALBey/JMokvRPKcdUJUWWduRfop44inaU=,tag:lo2GkhBLwZ54JP8UunruOQ==,type:str]
        serving.kserve.io/s3-usehttps: ENC[AES256_GCM,data:zg==,iv:2ggaYAL1dBvVU808GAB9opGCiseUTxA0hzTJYxqDX3Q=,tag:RapmPJMNOOIqGQvB6wRFvg==,type:str]
        serving.kserve.io/s3-verifyssl: ENC[AES256_GCM,data:JQ==,iv:NpoelLtnZDwjW5rUGitjp0GKuMLQbVNl8O+YfOxFqiA=,tag:eiPaFzoepOLNxXHBJdUVMQ==,type:str]
        serving.kserve.io/s3-region: ENC[AES256_GCM,data:boSpaNVLzria,iv:MWCHijLI7NgHpy0yyKR4Mjltas896+DqBbCoKRqnq48=,tag:NPCqjxCHWoScCdAaD9eoIg==,type:str]
        serving.kserve.io/s3-useanoncredential: ENC[AES256_GCM,data:OUP8d/U=,iv:7X7EIRX4RP6LUvp7xAFaqQ/j+2SaMWyMUUkD+2kvQF0=,tag:FHEvEg4koDIhcT84JD666Q==,type:str]
        serving.kserve.io/s3-usevirtualbucket: ENC[AES256_GCM,data:uzWpggI=,iv:1Ff96WgMNrNdvvM/d3QQ63g8/0ua6/f23H2ywXxEmdA=,tag:IH6W3TqTGqM0VlcapPIH5Q==,type:str]
type: ENC[AES256_GCM,data:Im0LMwZN,iv:C8+i2IvIbc08e5lEo466WgXTstozkN2LoxEj+AIpdkQ=,tag:BZeb/S8g4A3fZ9//OiLwvg==,type:str]
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Dn4gKqHbuN9b+xBlEEQbRg==,iv:A5KMDxVLw2wJkhjDvd9Hy8cAZOBMhYdC5KdiKGiITV0=,tag:7Q0LcfLP4xbTFKkSAPOOlw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BzvBVc3bOWu4XLn1h0cm6EbW7FY2c/5zgwn81YoSyDv6Whq2,iv:OBcCDHsuAHEL8ZEYgRxbZlN6Y+wYDuyIT0G68PO38tE=,tag:1MthQqYPX1tx2Gnq92fa3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUFZqK3RhZldRL2RSWm45
            RmoyejBCVXBncW1QSlBjMmRXcU9hRDZPM3dFCkhnakREWi9OSlRUcGZxRjZEY0Y5
            blpwRCtIalIvbTlMU3dVMGcwamNRbmMKLS0tIEFYNFplNituNSs3OHJ1U3FLdXkx
            TEx1WDZlTSsyaE1rRmNWUGNjaHhyUzAKJ3BvQESEnP57cRjtOQ6ERYOBkpm8AHI5
            qGsvxPu+L5Wb7qCreps+MHMIGGfQPKn3I21rehWEdU6LtxSSkVC1mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1962cwn3uhn3kp0m9qnk7vvfpzcydfuqdu5v7ph9klxux22n085asg63v9k
    lastmodified: "2026-06-30T12:14:07Z"
    mac: ENC[AES256_GCM,data:jkHa4PIuwGIXhlXQmZacWGwA2ET63NlPl4pKk4Lb8SD9HM2EZ48hWKTj1KSfYIIWT1AucBOvlGP1fGvFyMsulYGykTRGuDQ7R3EjK//XmZ+wO1k0EL1vHCXdk+V5Vup4nIIgfveAZhClxh3m1Xn7IEmcoVj8liStpzEG1ZjniMk=,iv:flAppS4NZndWxZkk6cuIhzzrlkr8QUXAlbOWMPKLi6U=,tag:kbZsz0hDC9b+b02CE0rx7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
