apiVersion: ENC[AES256_GCM,data:dEg=,iv:Ql/s/A2g4Qj9H+CGbgIMweB+9PzuyGo3A8GfDgdqNCw=,tag:iAJbhAQvsp7+WNazcWimCQ==,type:str]
kind: ENC[AES256_GCM,data:VTrcjWWt,iv:lvoQ3SGTBqiUAwSA0J2mwFrQ+GPOU8hnWpRvhZDFeD4=,tag:70TxFXnQbaEWdNlcNhzJZg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:odnKRZNU8BrG4I1rGeeppXY=,iv:ScZQ3EIsEl94+l7tCZjAnhMe+bbvGOOJWTr0DQmjmMI=,tag:Rgl64AnlEoZYPAI2TtliEQ==,type:str]
type: ENC[AES256_GCM,data:bMP9Xa1/,iv:J9h6E7sJFwE1wQrQnouKcSDuEWdwRmI5pFCyU0My6Wo=,tag:enjf6u2MA+Ichc/p4aBhuw==,type:str]
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:86Ubj4ri85BtDwn+WgxXuA==,iv:ylRnX/x8d7Dd+w4RGVeWHvAZB4WysQeXcrqOqxYLky0=,tag:N9OkgkbDjirlCUblA/3gpg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nZfEIHp/+EN/V0q0KuYEFyNZttpCfqCjOqvVCiPPFZw6VGF0,iv:BfMW8lCQnJO92vtm2LmM5YGxPU7Y8985ejGd0hsQ96o=,tag:bPqdtVtxaUeqOp8aaLfCvg==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:u3zsC9BSl/8=,iv:3s8qgn0wVfGsvBTJ018wj1ikvM3gWp3Rho2XbQaWxHg=,tag:hrv6yRT6qh5urJqZ9maNrw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:29f9nuTR/Qu2cyqcCYAhjS7ZPUA3MsQy,iv:dTRSz7daHz4+kNgH3Wkl2yAnUz5WGsOqceTYO0gN2g0=,tag:UMNKL9wG/xx3Kk0oRr9juQ==,type:str]
stringData:
    ENDPOINT: ENC[AES256_GCM,data:QqDSUHGumL/j9+REeIweIvfKf2pBToR5e9ROAtITMkihTw==,iv:EU059Cuf7V5JYvcAN23PYW3bTDdUv0lNn9ItvyDgtYE=,tag:jeohr0VndLeEmr3W5k2Pow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbURoUmdwQm5tb2pDeE9N
            bnJkeExmaHg0TFNyZ0QySUlETUUrSGFPc0E0CmV4ZlF2cml6MGtoazJMQVE0OVBG
            VlZOanI4T0wyT1VzWVFCQ3RnREFveG8KLS0tIGpjQ293dFd2SytxL0dIRFF4SzQz
            d2tYWG83Z0RBdzNoYzZOSWFvcm5hS28KXVdebz27Mz4GfTsBpjAwWOMjCRoPLMd7
            HjuR3pamh5sr42GA7QEHiRai9TCxiTthalPkU9eB8OGRrs6ESdmJMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1962cwn3uhn3kp0m9qnk7vvfpzcydfuqdu5v7ph9klxux22n085asg63v9k
    lastmodified: "2026-06-09T14:19:03Z"
    mac: ENC[AES256_GCM,data:jYfizNC04rZs2gpicHPb2EVGDDruBUuK7SbcxGqwiMh8CK5mr3kdTd3+QNcYdE8nRxCGJWIMwbMJqw0l2zeY+2dXt7HRx17/MGRtF+Z/QG318ewqtjzSgxwGkqZhsVLXopG1cODS/jW/5M2NON73KgNDFBK41klwN7TjTK98Fk0=,iv:xRoAgAHPmZrBT/HqU2eNGZ5SvikhCTGC1Mh9sHbHExo=,tag:84iQATtC27uEBRQSRHSDEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
