apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-job-policy
  namespace: minio
data:
  job-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "ManageModelsBucket",
          "Effect": "Allow",
          "Action": [
            "s3:CreateBucket",
            "s3:ListBucket",
            "s3:GetBucketLocation"
          ],
          "Resource": [
            "arn:aws:s3:::models"
          ]
        },
        {
          "Sid": "ReadWriteModelsObjects",
          "Effect": "Allow",
          "Action": [
            "s3:GetObject",
            "s3:PutObject"
          ],
          "Resource": [
            "arn:aws:s3:::models/*"
          ]
        }
      ]
    }
